### ISSUE TITLE
Cool work!

### ISSUE THREAD

**Issue by SkalskiP** [JVPC0D3R/gpt-voice-assistant#4]
Hi, @JVPC0D3R just want to let you know that I love the idea for the project. And I really love your pixel-art. I'm also really happy to see you used `supervision`.

**Comment by JVPC0D3R** [comment]
Thank you so much! I'll try to add more cool features soon. Love your videos btw, they're so helpful 🤠

**Comment by SkalskiP** [comment]
Fantastic to hear that! 🚀
